### ISSUE TITLE
KeyError: 'conv6_4'

### ISSUE THREAD

**Issue by jilljenn** [rezoo/illustration2vec#17]
Hi,

On Mac, I downloaded the models, but I can't load them. Seems like the loaded model does not have any layers, even if I use an old version of `chainer` (< 2.0).

Is it a Mac issue?

**Comment by sh0nk** [comment]
I have the same issue. Has anyone solved?

**Comment by sh0nk** [comment]
It had no error with the following version sets!

- python 2.7.15
- chainer 1.5.1

**Comment by jilljenn** [comment]
I'm surprised, because I still have the error on chainer 1.5.1.

    Traceback (most recent call last):
      File "run.py", line 13, in <module>
        illust2vec.estimate_plausible_tags([img], threshold=0.5)
      File "/Users/jilljenn/code/illustration2vec/i2v/base.py", line 95, in estimate_plausible_tags
        preds = self.estimate_top_tags(images, n_tag=512)
      File "/Users/jilljenn/code/illustration2vec/i2v/base.py", line 52, in estimate_top_tags
        prob = self._estimate(images)
      File "/Users/jilljenn/code/illustration2vec/i2v/base.py", line 42, in _estimate
        prob = self._extract(imgs, layername='prob')
      File "/Users/jilljenn/code/illustration2vec/i2v/chainer_i2v.py", line 57, in _extract
        h = self._forward(inputs, layername='conv6_4')
      File "/Users/jilljenn/code/illustration2vec/i2v/chainer_i2v.py", line 52, in _forward
        y, = self.net(inputs={'data': x}, outputs=[layername], train=False)
      File "/Users/jilljenn/code/illustration2vec/venv/lib/python2.7/site-packages/chainer/links/caffe/caffe_function.py", line 177, in __call__
        return tuple(variables[blob] for blob in outputs)
      File "/Users/jilljenn/code/illustration2vec/venv/lib/python2.7/site-packages/chainer/links/caffe/caffe_function.py", line 177, in <genexpr>
        return tuple(variables[blob] for blob in outputs)
    KeyError: 'conv6_4'
